platform :ios, "7.0"

pod 'AFNetworking','~> 2.6.3'
pod 'Mantle'
pod 'FMDB'
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'UMengAnalytics'
pod 'UzysAssetsPickerController'
pod 'UMengFeedback'

target :ScaAppTests, :exclusive => true do
# pod 'Kiwi'
end