platform :ios, "7.0"

pod 'AFNetworking','~> 2.6.3'
pod 'Mantle' ,'~> 1.5.6'
pod 'FMDB'
pod 'MJRefresh'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'UMengAnalytics'
pod 'UzysAssetsPickerController'
pod 'UMengFeedback'
pod 'Masonry'

target :ScaAppTests, :exclusive => true do
# pod 'Kiwi'
end